[package]
name = "velkhana/mushroom-tycoon"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
robloxformatnumber = "kiy4ku/robloxformatnumber@31.1.0"

[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"
